### ISSUE TITLE
Structure and explicitness

### ISSUE THREAD

**Issue by vbulant** [actum/frontend-checklist#1]
In the **Before development** block, I’ve polished the **Browser compatibility** and the **Dev stack** sections. I think it is the right balance of implicitness/explicitness.

Do you think it’s the right direction @janpanschab?

If so, @omladek can proceed in the similar direction with the rest of the document.

**Comment by janpanschab** [comment]
Great, let’s continue!

**Comment by vbulant** [comment]
Thanks, @omladek please proceed and let’s finalize the next iteration on the upcoming 1:1 👍
